ДЗ 1
RedSquid2212/2024-2-VK-EDU-Frontend-A-Shmantsar pull request #1
Opened 2024-09-21 15:44 UTC by RedSquid2212

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
* Дописаны функции в файлах `convertBytesToHuman.js`, `correctSentence.js`, `nonUniqueElements.js`
* Написаны тесты для функции `convertBytesToHuman`

2024-09-21 16:27 UTC, kgrechin requested changes
видел точно такое же решение один в один, даю доп занятия

2024-09-21 16:27 UTC, kgrechin commented on convertBytesToHuman.js
> +  while (bytes >= 1024 && index < units.length - 1) {
переписать на цикл for

2024-09-21 16:27 UTC, kgrechin commented on convertBytesToHuman.js
> +  const units = ['B', 'KB', 'MB', 'GB'];
тут могут быть терабайты и петабайты

2024-09-21 16:27 UTC, kgrechin commented on convertBytesToHuman.js
> +  const formattedBytes = parseFloat(bytes.toFixed(2)).toString();
можно сразу возвращать

2024-09-21 16:27 UTC, kgrechin commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman('bytes')).toBe(false)
добавить тесты на NaN, undefined, null, array, пустую строку

2024-09-21 16:27 UTC, kgrechin commented on convertBytesToHuman.test.js
> +test('Возвращает корректное значение для чисел', () => {
тесты для терабайтов и петабайтов

2024-09-21 16:27 UTC, kgrechin commented on correctSentence.test.js
> +  expect(correctSentence("greetings, friends")).toBe("Greetings, friends.")
добавить тесты типа:
expect(correctSentence("js_ts_kek_lol")).toBe("Js ts kek lol.")
expect(correctSentence("Kek_lol         javaScript Typescript")).toBe("Kek lol javascript typescript.")

+ придумать три теста от себя

2024-09-21 16:27 UTC, kgrechin commented on nonUniqueElements.js
> +  return data.filter(num => frequency[num] > 1);
переписать фильтр на цикл for

2024-09-21 16:27 UTC, kgrechin commented on nonUniqueElements.js
> +  const frequency = {};
добавить проверку входного значения

2024-09-21 16:27 UTC, kgrechin commented on nonUniqueElements.js
> +export default function nonUniqueElements(data) {
добавить доп параметр, по которому будет решаться, какой объект счетчик использовать Map или {}
написать декоратор для данной функции, который будет замерять время ее выполнения

сделать отдельный файлик c вызовами декорируемой функции и сравнивать время ее выполнения с Map и {}

2024-09-21 16:27 UTC, kgrechin commented on correctSentence.js
> +export default function correctSentence(text) {
добавить проверку входного значения

дополнить логику:
входная строка может быть с пробелами больше 1 символа
входная строка может быть с подчеркиваниями внутри
внутри строки могут быть слова с большой буквы

результат:
строка без подчеркиваний/длинных пробелов и все слова в ней должны быть с маленькой буквы кроме первого слова, в конце должны быть точка

2024-09-24 14:57 UTC, kgrechin requested changes

2024-09-24 14:57 UTC, kgrechin commented on nonUniqueElements.js
> +  if (!Array.isArray(data) || data.length === 0 || data.some(item => typeof item !== 'number' || !Number.isFinite(item))) {
Array.some - даст до цикл, давай в одном цикле проверять

2024-09-24 15:22 UTC, kgrechin approved these changes
@martinkomitsky, @HaseProgram, от меня аппрув

2024-09-25 20:49 UTC, HaseProgram approved these changes
12!

2024-09-25 20:50 UTC, merged