Done homework 2
RedSquid2212/2024-2-VK-EDU-Frontend-A-Shmantsar pull request #2
Opened 2024-10-03 11:44 UTC by RedSquid2212

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
* Сделана верстка для хэдера и формы
* Написан скрипт сохранения в localStorage

2024-10-03 12:02 UTC, RedSquid2212 commented
![localhost_8080_](https://github.com/user-attachments/assets/2c769622-e870-42f9-ad3d-9987f1d0fefa)

2024-10-04 06:41 UTC, kgrechin requested changes

2024-10-04 06:41 UTC, kgrechin commented on simple-chat/src/index.js
> +    messageElement.insertAdjacentHTML('beforeend', `${message.text} <span class="message-time">${message.from} at ${message.time}</span>`);
тут сейчас можно вставить любую верстку через инпут, нужно сделать чтобы добавляемые данные были текстом, лучше использовать innerText.

2024-10-04 06:41 UTC, kgrechin commented on simple-chat/src/index.js
> +        saveInLocalStorage(message);
давай работать с LS только в момент загрузки сообщений и в момент анмаунта страницы для выгрузки, а так использовать локальный стейт

2024-10-04 06:41 UTC, kgrechin commented on simple-chat/src/index.html
> +        <div class="message-list"></div>
нужно добавить отображение сообщений от собеседника, можно просто версткой их сюда захардкодить.
плюс сообщений должны быть прибиты книзу (к инпуту), сейчас они прибиты к хедеру

2024-10-08 05:15 UTC, kgrechin commented
@RedSquid2212, ждем фиксов)

2024-10-10 07:20 UTC, kgrechin requested changes

2024-10-10 07:20 UTC, kgrechin commented on simple-chat/src/messages.css
> +.message-list {
<img width="409" alt="Снимок экрана 2024-10-10 в 10 18 03" src="https://github.com/user-attachments/assets/ec2190d2-982e-4033-b404-b3d702b64d45">
<img width="889" alt="Снимок экрана 2024-10-10 в 10 18 30" src="https://github.com/user-attachments/assets/39ea2ded-7892-4903-96ce-87765e3cfa84">

@RedSquid2212, все круто, осталось только пофиксить отображение длинных сообщений и мобильное вью - слишком мелким все выглядит

2024-10-13 10:02 UTC, kgrechin requested changes
@RedSquid2212

2024-10-15 05:54 UTC, kgrechin approved these changes
@RedSquid2212 на будущие дз - сделать чтобы скролл был не на всей странице чата, а только у блока с сообщениями, плюс реализовать подскролл к новому сообщению, плюс подумать насчет ограничения максимальной ширины мессенджера, на широких экранах растягивается и выглядит не очень

@HaseProgram , @martinkomitsky  аппрув

2024-10-17 20:34 UTC, merged

2024-10-17 20:34 UTC, martinkomitsky commented
12!