Exam
RedSquid2212/2024-2-VK-EDU-Frontend-A-Shmantsar pull request #9
Opened 2024-12-23 18:20 UTC by RedSquid2212

# Экзамен

Прошу @martinkomitsky, @haseprogram проверить его.

Что было сделано:
* Создано базовое приложение в корневом каталоге
* Сверстаны две страницы (главная и с историей)
* Использованы стили (но не все на момент открытия ПР)
* Реализован перевод с одного языка на другой (пока без выбора в селекте)
* Использован react-router
* Приложение задеплоено

Постараюсь до конца дня доделать все, что не было доделано

2024-12-28 12:52 UTC, HaseProgram requested changes
Привет, хорошая работа, много всего реализовано, лайк.

Из замечаний - немного поехавшая верстка и не кликающиеся кнопки языков - можно пофиксить за доп 4 балла.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/939548f4-2a51-46df-a1c0-2b5f09bd75c9" />

2024-12-28 12:52 UTC, HaseProgram commented on exam/src/components/CardsHeader/CardsHeader.tsx
> +            <LanguageCheckbox language='SPANISH'/>
Не кликаются, нет обработчика)

2024-12-28 12:52 UTC, HaseProgram commented on exam/src/components/CardsHeader/CardsHeader.tsx
> +            <LanguageCheckbox language='SPANISH'/>
Аналогично

2024-12-28 18:24 UTC, RedSquid2212 commented on exam/src/components/CardsHeader/CardsHeader.tsx
> +            <LanguageCheckbox language='SPANISH'/>
Хорошо, спасибо, поправлю завтра

2025-01-12 18:44 UTC, HaseProgram approved these changes
Супер, добавил до 42)

2025-01-12 18:45 UTC, merged